# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('end', models.DateField(unique=True, verbose_name='end')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Testing'), (4, 'Done')], default=1, verbose_name='status')),
                ('order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('started', models.DateField(blank=True, null=True, verbose_name='started')),
                ('due', models.DateField(blank=True, null=True, verbose_name='due')),
                ('completed', models.DateField(blank=True, null=True, verbose_name='completed')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='assigned')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Sprint', verbose_name='Sprint')),
            ],
        ),
    ]
